books/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_books, name="books"),
    path('<int:book_id>/', views.book_detail, name="book_detail"),
    path('add/', views.add_book, name="add_book"),
    path('edit/<int:book_id>', views.edit_book, name="edit_book"),
    path('delete/<int:book_id>', views.delete_book, name="delete_book"),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>', views.adjust_cart, name='adjust_cart'),
    path('remove_from_cart/<item_id>/',
         views.remove_from_cart, name='remove_from_cart'),
]

thebookzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('books/', include('books.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Author(models.Model):

    name = models.CharField(max_length=254, null=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    category = models.ForeignKey('Category', null=True,
                                 blank=True, on_delete=models.SET_NULL)
    isbn13 = models.CharField(max_length=254, null=True, blank=True)
    isbn10 = models.CharField(max_length=254, null=True, blank=True)
    title = models.CharField(max_length=254)
    author = models.ForeignKey('Author', null=True,
                                 blank=True, on_delete=models.SET_NULL)
    image = models.ImageField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    description = models.TextField(max_length=9999)
    book_format = models.BooleanField(default=False, null=True, blank=True)
    published_year = models.CharField(max_length=4, default=None)
    rating = models.DecimalField(max_digits=6, decimal_places=2,
                                 null=True, blank=True)
    num_pages = models.CharField(max_length=6, default=None)
    ratings_count = models.CharField(max_length=254, default=None)

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from .models import Book, Category
from .widgets import CustomClearableFileInput


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = '__all__'

    image = forms.ImageField(label='Image',
                             required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-10'

books/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.db.models import Q
from .models import Book, Category
from .forms import BookForm
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required


def all_books(request):
    """ A view to return all book, including sorting and search queries """

    books = Book.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                books = books.annotate(lower_name=Lower('title'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            books = books.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            books = books.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('books'))

            queries = Q(title__icontains=query) |\
                Q(description__icontains=query) | Q(author__icontains=query)
            books = books.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'books': books,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'books/books.html', context)


def book_detail(request, book_id):
    """ A view to show individual book details """

    book = get_object_or_404(Book, pk=book_id)

    context = {
        'book': book,
    }

    return render(request, 'books/book_detail.html', context)


@login_required
def add_book(request):
    """ Add a book to the library """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()
            messages.success(request, 'Successfull aded book!')
            return redirect(reverse('book_detail', args=[book.id]))
        else:
            messages.error(request,
                           'Failed to add book.\
                            Please ensure the form is valid.')
    else:
        form = BookForm()
    template = 'books/add_book.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_book(request, book_id):
    """ edit a book in the library """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    book = get_object_or_404(Book, pk=book_id)

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated book!')
            return redirect(reverse('book_detail', args=[book.id]))
        else:
            messages.error(request, 'Failed to update book. \
                                     Please ensure the form is valid.')
    else:
        form = BookForm(instance=book)
        messages.info(request, f'You are editing {book.title}')

    template = 'books/edit_book.html'
    context = {
        'form': form,
        'book': book,
    }
    return render(request, template, context)


@login_required
def delete_book(request, book_id):
    """ delete a book from the library """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    book = get_object_or_404(Book, pk=book_id)

    book.delete()
    messages.success(request, 'Book deleted!')
    return redirect(reverse('books'))

books/templates/books/add_book.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container text-salmon">
        <div class="row">
            <div class="col text-align">
                <hr>
                <h2 class="logo-font mb-4">Book Management</h2>
                <h5 class="text-muted">Add a Book</h5>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <form method="POST" action="{% url 'add_book' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                <div class="text-right">
                    <a href="{% url 'books' %}" class="btn btn-outline-black rounded-10">Cancel</a>
                    <button class="btn btn-black rounded-10" type="submit">Add Book</button>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

books/templates/books/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if book.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid img-size" src="{{ book.image.url }}" alt="{{ book.name }}">
                        </a>
                    {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ book.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="book-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ book.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">€{{ book.price }}</p>
                    {% if book.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'books' %}?category={{ book.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ book.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if book.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ book.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_book' book.id %}">Edit</a>
                            <a href="{% url 'delete_book' book.id %}" class="text-danger">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ book.description }}</p>
                    <form class="form" action="{% url 'add_to_cart' book.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with book.book_format as f %}
                            {% if f %}
                                <div class="col-12">
                                    <p><strong>Format:</strong></p>
                                    <select class="form-control rounded-10 w-50" name="book_format" id="id_book_format">
                                        <option value="Hardback" selected>Hardback</option>
                                        <option value="Paperback">Paperback</option>
                                        <option value="Digital Download">Digital Download</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-10" data-item_id="{{ book.id }}" id="decrement-qty_{{ book.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ book.id }}"
                                            id="id_qty_{{ book.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-10" data-item_id="{{ book.id }}" id="increment-qty_{{ book.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col{% if v %}-12 mt-2{% endif %}">
                                <a href="{% url 'books' %}" class="btn btn-outline-black rounded-10 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-10 text-uppercase mt-5" value="Add to Cart">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'books/includes/quantity_input_script.html' %}
{% endblock %}

books/templates/books/books.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3">
                <h2 class="logo-font">Books</h2>
                {% for c in current_categories %}
                    <a class="category-badge text-decoration-none" href="{% url 'books' %}?category={{ c.name }}">
                        <span class="p-2 mt-2 badge badge-white text-salmon rounded-10 border border-dark">{{ c.friendly_name }}</span>
                    </a>
                {% endfor %}
                <hr class="w-50 mb-1">
            </div>
        </div>
        <div class="row">
            <div class="product-container col-10 offset-1">
                <div class="row mt-1 mb-2">
                    <div class="col-12 col-md-6 my-auto pb-2 pr-0 order-md-last d-flex justify-content-center justify-content-md-end">
                        <div class="sort-select-wrapper w-50">
                            <select id="sort-selector" class="custom-select custom-select-sm rounded-10 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                                <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                                <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                                <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Title (A-Z)</option>
                                <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Title (Z-A)</option>
                                <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)</option>
                                <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-md-first">
                        <p class="text-muted mt-3 text-center text-md-left">
                            {% if search_term or current_categories or current_sorting != 'None_None' %}
                                <span class="small"><a href="{% url 'books' %}">Books Home</a> | </span>
                            {% endif %}
                            {{ books|length }} Books{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
                </div>
                    <div class="row">
                        {% for book in books %}
                            <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                                <div class="card h-100 border-0">
                                    {% if book.image %}
                                    <a href="{% url 'book_detail' book.id %}">
                                        <img class="card-img-top img-fluid img-size" src="{{ book.image.url }}" alt="{{ book.name }}">
                                    </a>
                                    {% else %}
                                    <a href="{% url 'book_detail' book.id %}">
                                        <img class="card-img-top img-fluid img-size" src="{{ MEDIA_URL }}noimage.png" alt="{{ book.name }}">
                                    </a>
                                    {% endif %}
                                    <div class="card-body pb-0">
                                        <p class="mb-0">{{ book.title }} <em>by</em></p>
                                        <p><strong>{{ book.author }}</strong></p>
                                    </div>
                                    <div class="card-footer bg-white pt-0 border-0 text-left">
                                        <div class="row">
                                            <div class="col">
                                                <p class="lead mb-0 text-left font-weight-bold">€{{ book.price }}</p>
                                                {% if book.category %}
                                                <p class="small mt-1 mb-0">
                                                    <a class="text-muted" href="{% url 'books' %}?category={{ book.category.name }}">
                                                        <i class="fas fa-tag mr-1"></i>{{ book.category.friendly_name }}
                                                    </a>
                                                </p>
                                                {% endif %}
                                                {% if book.rating %}
                                                    <small class="text-muted"><i class="fas fa fa-star mr-1"></i>{{ book.rating }} / 5</small>
                                                {% else %}
                                                    <small class="text-muted">No Rating</small>
                                                {% endif %}
                                                {% if request.user.is_superuser %}
                                                    <small class="ml-3">
                                                        <a href="{% url 'edit_book' book.id %}">Edit</a>
                                                        <a href="{% url 'delete_book' book.id %}" class="text-danger">Delete</a>
                                                    </small>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% if forloop.counter|divisibleby:1 %}
                                <div class="col-12 d-sm-none mb-5">
                                    <hr>
                                </div>
                            {% endif %}                        
                            {% if forloop.counter|divisibleby:2 %}
                                <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                    <hr>
                                </div>
                            {% endif %}
                            {% if forloop.counter|divisibleby:3 %}
                                <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                    <hr>
                                </div>
                            {% endif %}
                            {% if forloop.counter|divisibleby:4 %}
                                <div class="col-12 d-none d-xl-block mb-5">
                                    <hr>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    <div class="btt-button shadow-sm rounded-10 border border-black">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-arrow-up mx-auto my-auto"></i>
        </a>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('.btt-link').click(function(e) {
            window.scrollTo(0,0)
        })
    </script>

    <script type="text/javascript">
        $('#sort-selector').change(function(){
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");
                
                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}

books/templates/books/edit_book.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container text-salmon">
        <div class="row">
            <div class="col-12 text-align">
                <hr>
                <h2 class="logo-font mb-4">Book Management</h2>
                <h5 class="text-muted">Edit a Book</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <form method="POST" action="{% url 'edit_book' book.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                <div class="text-right">
                    <a href="{% url 'books' %}" class="btn btn-outline-black rounded-10">Cancel</a>
                    <button class="btn btn-black rounded-10" type="submit">Update Book</button>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}